name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main   # Runs only when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: gopi2005                   # Your Docker Hub username
          password: ${{ secrets.DOCKER_HUB_PAT }}  # Secret with PAT

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t gopi2005/cloudvault:latest .
          docker push gopi2005/cloudvault:latest

      # Step 4: SSH into droplet and deploy
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            docker pull gopi2005/cloudvault:latest
            docker stop cloudvault-container || true
            docker rm cloudvault-container || true
            docker run -d -p 80:5000 --name cloudvault-container gopi2005/cloudvault:latest
