name: Deploy React to Digital Ocean
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Fixed login step
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            your-dockerhub-username/your-app:${{ github.sha }}
            your-dockerhub-username/your-app:latest

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            docker pull your-dockerhub-username/your-app:${{ github.sha }} || docker pull your-dockerhub-username/your-app:latest
            docker stop your-container || true
            docker rm your-container || true
            docker run -d -p 80:80 --name your-container your-dockerhub-username/your-app:${{ github.sha }}
