name: Deploy React to Digital Ocean
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gopi2005/cloudvault:${{ github.sha }}
            gopi2005/cloudvault:latest

      - name: Deploy to Digital Ocean droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            docker pull gopi2005/cloudvault:${{ github.sha }} || docker pull gopi2005/cloudvault:latest
            docker rm -f cloudvault-container || true
            docker run -d \
              --name cloudvault-container \
              -p 80:80 \  # Map host port 80 to container port 80 (Nginx)
              --restart unless-stopped \
              gopi2005/cloudvault:${{ github.sha }}
